In [1]:
import numpy as np
import math
import Bio

In [98]:
score_matrix = np.array([[-math.inf, -1, -1, -1, -1],
                         [-1, 1, -1, -1, -1],
                         [-1, -1, 1, -1, -1],
                         [-1, -1, -1, 1, -1],
                         [-1, -1, -1, -1, 1]])

def smtx(a,b):
    if a == "-":
        if b == "-":
            return -math.inf
        return -0.5
    if a == b:
        return 1
    if b == "-":
        return -0.5
    else:
        return 0

testo = "GCATGCA"
testt = "GATTACA"

NWA now seems to work, just need to implement backtracking algorithmically to find optimal alignment/solution

In [89]:
def NWA(seqa,seqb,fact):
    grid = np.zeros((len(seqa)+1,len(seqb)+1))
    srow = []
    for i in range(len(seqb)+1):
        srow.append(0-fact*i)
    for i in range(len(seqa)+1):
        grid[i][0] = 0-fact*i
    grid[0] = srow
    midgrid = grid[1:,1:]
    for x in range(1,len(seqa)+1):
        for y in range(1,len(seqb)+1):
            grid[x][y] = max((grid[x-1][y-1]+smtx(seqa[x-1],seqb[y-1])),
                             (grid[x-1][y]+smtx(seqa[x-1],"-")),
                             (grid[x][y-1]+smtx("-",seqb[y-1])))
    print(grid)

    return grid

^^THIS IS RIGHT - IT BUILDS THE CORRECT MATRIX

In [90]:
test = NWA(testo,testt,1)

[[ 0. -1. -2. -3. -4. -5. -6. -7.]
 [-1.  1.  0. -1. -2. -3. -4. -5.]
 [-2.  0.  0. -1. -2. -3. -2. -3.]
 [-3. -1.  1.  0. -1. -1. -2. -1.]
 [-4. -2.  0.  2.  1.  0. -1. -2.]
 [-5. -3. -1.  1.  1.  0. -1. -2.]
 [-6. -4. -2.  0.  0.  0.  1.  0.]
 [-7. -5. -3. -1. -1.  1.  0.  2.]]


In [ ]:
actual1 = "CAAAGACCTGAAGAGCCAGTGGACTCCACCCCACTTTCTGGTCTGACCAATT"
actual2 = "ACCACACTCTCTGGGCTGACCAATTACAGCGCTTCTACAGAACTGAAGACTCC"

NWA(actual1,actual2,0.5)

In [ ]:
def optPath(mtx, wrd1, wrd2):
    reverse = []
    char1 = len(wrd1)-1
    char2 = len(wrd2)-1
    x = mtx.shape[0]-1
    y = mtx.shape[1]-1
    #left = mtx[x][y-1]
    #up = mtx[x-1][y]
    #diag = mtx[x-1][y-1]
    #if diag>=up and diag>=left:
    #    reverse.append([wrd1[char1],wrd2[char2]])
    #    char1 = char1-1
    #    char2 = char2-1
    #elif up>=left:
        
    while not(x==0 and y==0):
        left = mtx[x][y-1]
        up = mtx[x-1][y]
        diag = mtx[x-1][y-1]
        print(y,x)
        print(up,left,diag)
        if diag>=up and diag>=left:
            x=x-1
            y=y-1
            reverse.append([wrd1[char1],wrd2[char2]])
            char1 = char1-1
            char2 = char2-1
        elif up>left:
            x=x-1
            reverse.append(["-",wrd2[char2]])
            char2 = char2-1
        else:
            y=y-1
            reverse.append([wrd1[char1],"-"])
            char1 = char1-1
    print(reverse)
            

In [ ]:
optPath(test, testo, testt)

^^THIS IS WRONG - IT GETS THE WRONG MATCHINGS

In [ ]:
p = "CAGAGG"
q = "CATGAG"
grid = NWA(q,p,1)

In [ ]:
optPath(grid, q, p)

[[  0.   -0.5  -1.  ... -25.5 -26.  -26.5]
 [ -0.5  -1.    0.5 ... -24.5 -24.5 -25. ]
 [ -1.    0.5  -0.5 ... -24.5 -25.5 -25.5]
 ...
 [-25.  -23.5 -23.5 ...   0.   -1.   -1. ]
 [-25.5 -24.5 -24.5 ...   2.    1.    0. ]
 [-26.  -25.5 -25.5 ...   2.    1.    0. ]]


array([[  0. ,  -0.5,  -1. , ..., -25.5, -26. , -26.5],
       [ -0.5,  -1. ,   0.5, ..., -24.5, -24.5, -25. ],
       [ -1. ,   0.5,  -0.5, ..., -24.5, -25.5, -25.5],
       ...,
       [-25. , -23.5, -23.5, ...,   0. ,  -1. ,  -1. ],
       [-25.5, -24.5, -24.5, ...,   2. ,   1. ,   0. ],
       [-26. , -25.5, -25.5, ...,   2. ,   1. ,   0. ]])

In [92]:
def optPath(mtx, wrd1, wrd2):
    reverse = []
    char1 = len(wrd1)-1
    char2 = len(wrd2)-1
    x = mtx.shape[0]-1
    y = mtx.shape[1]-1
    #left = mtx[x][y-1]
    #up = mtx[x-1][y]
    #diag = mtx[x-1][y-1]
    #if diag>=up and diag>=left:
    #    reverse.append([wrd1[char1],wrd2[char2]])
    #    char1 = char1-1
    #    char2 = char2-1
    #elif up>=left:
        
    while not(x==0 and y==0):
        left = mtx[x][y-1]
        up = mtx[x-1][y]
        diag = mtx[x-1][y-1]
        print(y,x)
        print(up,left,diag)
        if diag>=up and diag>=left:
            x=x-1
            y=y-1
            reverse.append([wrd1[char1],wrd2[char2]])
            char1 = char1-1
            char2 = char2-1
        elif up>left:
            x=x-1
            reverse.append(["-",wrd2[char2]])
            char2 = char2-1
        else:
            y=y-1
            reverse.append([wrd1[char1],"-"])
            char1 = char1-1
    print(reverse)
            

In [93]:
optPath(test, testo, testt)

7 7
0.0 0.0 1.0
6 6
-1.0 0.0 0.0
5 5
0.0 1.0 1.0
4 4
-1.0 2.0 0.0
3 4
0.0 0.0 1.0
2 3
0.0 -1.0 0.0
1 2
1.0 -2.0 -1.0
1 1
-1.0 -1.0 0.0
[['A', 'A'], ['C', 'C'], ['G', 'A'], ['T', '-'], ['A', 'T'], ['C', 'T'], ['-', 'A'], ['G', 'G']]


^^THIS IS WRONG - IT GETS THE WRONG MATCHINGS

In [96]:
p = "CAGAGG"
q = "CATGAG"
grid = NWA(q,p,1)

[[ 0. -1. -2. -3. -4. -5. -6.]
 [-1.  1.  0. -1. -2. -3. -4.]
 [-2.  0.  2.  1.  0. -1. -2.]
 [-3. -1.  1.  1.  0. -1. -2.]
 [-4. -2.  0.  2.  1.  1.  0.]
 [-5. -3. -1.  1.  3.  2.  1.]
 [-6. -4. -2.  0.  2.  4.  3.]]


In [97]:
optPath(grid, q, p)

6 6
1.0 4.0 2.0
5 6
2.0 2.0 3.0
4 5
1.0 1.0 2.0
3 4
1.0 0.0 1.0
2 3
2.0 -1.0 0.0
2 2
0.0 0.0 1.0
1 1
-1.0 -1.0 0.0
[['G', '-'], ['A', 'G'], ['G', 'G'], ['T', 'A'], ['-', 'G'], ['A', 'A'], ['C', 'C']]
