In [1]:
import Bio
import numpy as np
import math

In [5]:
dist = np.array([[0, 12, 14, 14, 15],
                 [12, 0, 12, 12, 13],
                 [14, 12, 0, 6, 7],
                 [14, 12, 6, 0, 3],
                 [15, 13, 7, 3, 0]])
taxa = ["a","b","c","d","e"]

In [28]:
def NJM(taxa,mtx):
    r_taxa = []
    for i in range(len(taxa)):
        res = 0
        for j in range(len(taxa)):
            res += mtx[i][j]
        r_taxa.append(res)
    print(r_taxa)
    print(mincomb(r_taxa,mtx))
    merge(mincomb(r_taxa,mtx)[0],mincomb(r_taxa,mtx)[1],r_taxa,mtx)

def mincomb(taxa,mtx):
    res = [math.inf,math.inf]
    thresh = math.inf
    for i in range(len(taxa)):
        for j in range(len(taxa)):
            if i==j:
                continue
            mini = mtx[i][j] - (taxa[i]+taxa[j])/(len(taxa)-2)
            if mini<thresh:
                thresh = mini
                res = [i,j]
    return res

def merge(i,j,taxa,mtx):
    distj = 0.5* (mtx[i][j]+(taxa[j]-taxa[i])/(len(taxa)-2))
    disti = 0.5* (mtx[i][j]+(taxa[i]-taxa[j])/(len(taxa)-2))
    
    print(disti,distj)
    
    newdists = []
    for x in range(mtx.shape[0]):
        if x!=i and x!=j:
            temp = (mtx[i][x]+mtx[j][x]-mtx[i][j])/2
            newdists.append(temp)
    newdists.append(0)
    
    umtx = np.zeros((mtx.shape[0]-1,mtx.shape[0]-1))
    umtx[mtx.shape[0]-2] = newdists
    for n in range(mtx.shape[0]-2):
        umtx[n][mtx.shape[0]-2] = newdists[n]
    print(umtx)
    
def updateMtx(i,j,mtx,mergedists):
    np.delete(mtx,i,0)
    np.delete(mtx,i,1)
    np.delete(mtx,j,0)
    np.delete(mtx,j,1)
    
    
            

In [29]:
NJM(taxa,dist)

[55, 49, 39, 35, 38]
[0, 1]
7.0 5.0
[[0. 0. 0. 7.]
 [0. 0. 0. 7.]
 [0. 0. 0. 8.]
 [7. 7. 8. 0.]]
